spring:
  application:
    name: user
  cloud:
    refresh:
      refreshable: none
      stream:
         bindings:
            output:
               destination: user-exchange
               binder: rabbit1
server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
