server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      registerWithEureka: true
      fetchRegistry: true
  instance:
    leaseRenewalIntervalInSeconds: 5
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    preferIpAddress: true
management:
  security:
    enabled: false
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
        base-path: /actuator
    cors:
      allowed-origins: true
      enabled-by-default: false
spring:
  boot.admin.client:
    url: http://localhost:8763
    username: admin
    password: password
  cloud:
    stream:
      bindings:
        userNewChannel:
          destination: user.new.exchange
          contentType: application/json
          binder: rabbit1
        userDeleteChannel:
          destination: user.delete.exchange
          contentType: application/json
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest

