server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
spring:
  application:
    name: campsite
  cloud:
    stream:
      bindings:
        campsiteNewChannel:
          destination: campsite.new.exchange
          contentType: application/json
          binder: rabbit1
        campsiteDeleteChannel:
          destination: campsite.delete.exchange
          contentType: application/json
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest