server:
  port: 8762

spring:
  application:
    name: zuul

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      registerWithEureka: true
      fetchRegistry: true  
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    preferIpAddress: true
   
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
