server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
management:
  security:
    enabled: false
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
        base-path: /actuator
    cors:
      allowed-origins: true
      enabled-by-default: false
spring:
  application: 
    name: ^project.artifactId^
    version: ^project.version^
    title: ^project.name^
  profiles:
    active: default
  resources:
    add-mappings: true
  mvc:
    throw-exception-if-no-handler-found: true
  cloud:
    stream:
      bindings:
        campsiteNewChannel:
          destination: campsite.new.exchange
          binder: rabbit1
        campsiteDeleteChannel:
          destination: campsite.delete.exchange
          binder: rabbit1
        userNewChannel:
          destination: user.new.exchange
          binder: rabbit1
        userDeleteChannel:
          destination: user.delete.exchange
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
  boot.admin.client:
    url: http://localhost:8763
    username: admin
    password: password
    
springfox:
  documentation:
    swagger:
      v2:
        path: "/swagger"
    
validation:
  reservation:
    max:
      days:
        exceeded:
          msg: Reservation max. days exceeded
    availability:
      msg: Dates already take it
    anticipate:
      days:
        error:
          msg: Not allowed reservation dates
    date:
      days:
        error:
          msg: Arrival date is after Departure date
