server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS::http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
management:
  security:
    enabled: false
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
        base-path: /actuator
    cors:
      allowed-origins: true
      enabled-by-default: false
spring:
  application: 
    name: ^project.artifactId^
    version: ^project.version^
    title: ^project.name^
  boot.admin.client:
    url: http://localhost:8763
    username: admin
    password: password
