#server:
#  port: 0
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#    preferIpAddress: true
#    leaseRenewalIntervalInSeconds: 5
eureka:
  client:
    enabled: false
management:
  security:
    enabled: false
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
        base-path: /actuator
    cors:
      allowed-origins: true
      enabled-by-default: false
spring:
  application: 
    name: ^project.artifactId^
    version: ^project.version^
    title: ^project.name^
    resources:
      add-mappings: true
  profiles:
    active: local
  cloud:
    stream:
      bindings:
        campsiteNewChannel:
          destination: campsite.new.exchange
          binder: rabbit1
        campsiteDeleteChannel:
          destination: campsite.delete.exchange
          binder: rabbit1
        userNewChannel:
          destination: user.new.exchange
          binder: rabbit1
        userDeleteChannel:
          destination: user.delete.exchange
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: ${RABBITMQ_SERVICE_HOST:localhost}
                port: ${RABBITMQ_SERVICE_PORT:5672}
                username: ${RABBITMQ_USERNAME:guest}
                password: ${RABBITMQ_PASSWORD:guest}
    config:
      enabled: false
      discovery:
        enabled: false
#  boot.admin.client:
#    url: http://localhost:8763
#    username: admin
#    password: password
