FROM openjdk:8-jdk-alpine
LABEL maintainer="mauricio.aiello@gmail.com"
VOLUME /tmp
ARG JAR_FILE=target/eureka-server-0.0.1-SNAPSHOT.jar
ADD ${JAR_FILE} eureka-server.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/eureka-server.jar"]
