server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
endpoints:
  sensitive: false
spring:
  application: 
    name: ^project.artifactId^
    version: ^project.version^
    title: ^project.name^